version: '1.0'
services: 
    web:
        image: 'httpd'
        ports:
            - "80:80"
        volumes:
            - ~/Documents/GitHub/dwwm2024/js/object/exercices:/usr/local/apache2/htdocs/